-- kanshi-mode.lua — NWG-DISPLAYS MODE
-- Managed by enable-kanshi / disable-kanshi — do not edit manually.
--
-- nwg-displays mode: require monitors.lua (generated by nwg-displays).
-- kanshi mode:       start kanshi and do NOT require monitors.lua.
require("monitors")
