#!/bin/bash
# Launch waybar with workspace assignments per monitor

# Kill any existing waybar instances
killall waybar 2>/dev/null

# Wait a moment for processes to terminate
sleep 0.5

# The CPU module needs one icon placeholder per logical core. Generate the
# account/machine-specific CPU and memory definitions before Waybar reads them.
WAYBAR_GENERATOR="${HOME}/hyprconfig/install/waybar.sh"
if [[ -x "$WAYBAR_GENERATOR" ]] && ! "$WAYBAR_GENERATOR"; then
    echo "warning: failed to generate Waybar CPU and memory modules" >&2
fi

# Monitor variables — sourced from monitor-env.sh (generated by apply-monitor-vars.sh).
# Edit connector names in ~/.config/hypr/hyprland/monitor-vars.conf, not here.
MONITOR_ENV="${HOME}/.config/hypr/monitor-env.sh"
if [[ -f "$MONITOR_ENV" ]]; then
    # shellcheck source=/dev/null
    source "$MONITOR_ENV"
else
    echo "warning: ${MONITOR_ENV} not found, falling back to defaults" >&2
    export MONITOR1="DP-1"
    export MONITOR2="DP-6"
    export MONITOR3="eDP-1"
fi

MONITOR_LEFT="$MONITOR1"    # Workspaces 1-8
MONITOR_MIDDLE="$MONITOR2"  # Workspaces 9-16
MONITOR_RIGHT="$MONITOR3"   # Workspaces 17-20

# Let Hyprland finish registering outputs before Waybar creates layer surfaces.
# This prevents a top bar started during login from binding only to the first
# monitor that happened to be ready.
previous_output_count=""
for _ in {1..20}; do
    output_count="$(hyprctl monitors -j 2>/dev/null | jq 'length' 2>/dev/null || true)"
    if [[ -n "$output_count" && "$output_count" == "$previous_output_count" ]]; then
        break
    fi
    previous_output_count="$output_count"
    sleep 0.25
done

# Hyprland 0.56+ Lua config rejects waybar's legacy "dispatch workspace N"
# (clicking a workspace). Run waybar behind the command-socket translation shim
# so those dispatches are rewritten to the Lua form. See
# ~/hyprconfig/hypr-lua-shim/README.md
SHIM_DIR="${HOME}/hyprconfig/hypr-lua-shim"
if [[ -x "$SHIM_DIR/shim-up.sh" ]] && "$SHIM_DIR/shim-up.sh" waybar; then
    export HYPRLAND_INSTANCE_SIGNATURE="waybar"
else
    echo "warning: hypr-lua-shim not available; workspace clicks may not work" >&2
fi

# Launch top bar
waybar -c ~/.config/waybar/config-top -s ~/.config/waybar/style.css &

# Launch bottom bar (single instance handles all monitors)
waybar -c ~/.config/waybar/config-bottom -s ~/.config/waybar/style.css &

echo "Waybar launched with workspace assignments:"
echo "  - $MONITOR_LEFT: workspaces 1-8"
echo "  - $MONITOR_MIDDLE: workspaces 9-16"
echo "  - $MONITOR_RIGHT: workspaces 17-20"
