alias senable="sudo systemctl enable --now"
alias sdisable="sudo systemctl disable --now"
alias sstart="sudo systemctl start"
alias sstop="sudo systemctl stop"
alias srestart="sudo systemctl restart"
alias sstatus="sudo systemctl status"
