#!/usr/bin/env bash
#
# waybar.sh — install-time waybar configuration.
#
# Generates host-specific waybar module files:
#
#   modules-cpu.jsonc    — one bar icon slot per logical CPU core (from nproc).
#                          The built-in "cpu" module only populates {iconN}
#                          placeholders up to the actual core count; extra
#                          placeholders render as literal text and break the
#                          widget, so the count must match the hardware.
#
#   modules-memory.jsonc — RAM display, plus SWAP if swap is configured.
#                          Click toggles RAM <-> SWAP; hover shows both.
#                          If no swap is present, only RAM is shown.
#
# Both files are included by config-top / config-bottom and are gitignored.
# Re-run this script if you move the config to a machine with a different core
# count or swap configuration.

set -euo pipefail

WAYBAR_DIR="${WAYBAR_DIR:-$HOME/.config/waybar}"
OUT_CPU="${WAYBAR_DIR}/modules-cpu.jsonc"
OUT_MEM="${WAYBAR_DIR}/modules-memory.jsonc"

mkdir -p "$WAYBAR_DIR"

# ── CPU: one {iconN} slot per logical core ───────────────────────────────────
CORES="$(nproc)"
[[ "$CORES" -ge 1 ]] || CORES=1

ICONS=""
for ((i = 0; i < CORES; i++)); do
    ICONS+="{icon${i}}"
done

cat > "$OUT_CPU" << EOF
// Generated by install/waybar.sh — do not edit manually.
// One {iconN} slot per logical CPU core (detected: ${CORES}).
{
  "cpu": {
    "interval": 1,
    "format": "<span color='#ef9f76'>CPU:</span> ${ICONS}",
    "format-icons": [
      "<span color='#69ff94'>▁</span>",
      "<span color='#2aa9ff'>▂</span>",
      "<span color='#f8f8f2'>▃</span>",
      "<span color='#f8f8f2'>▄</span>",
      "<span color='#ffffa5'>▅</span>",
      "<span color='#ffffa5'>▆</span>",
      "<span color='#ff9977'>▇</span>",
      "<span color='#dd532e'>█</span>"
    ]
  }
}
EOF

echo "Generated ${OUT_CPU} for ${CORES} CPU core(s)."

# ── Memory: RAM always, SWAP if configured ───────────────────────────────────
# Detect whether any swap device/file is active.
if [[ -n "$(swapon --show --noheadings 2>/dev/null)" ]]; then
    HAS_SWAP=1
else
    HAS_SWAP=0
fi

if [[ "$HAS_SWAP" -eq 1 ]]; then
    cat > "$OUT_MEM" << 'EOF'
// Generated by install/waybar.sh — do not edit manually.
// Swap detected: click toggles RAM <-> SWAP, hover shows both.
{
  "memory": {
    "interval": 5,
    "format": "<span color='#7287fd'>RAM:</span> <span color='#99d1db'>{used:0.1f}G</span>/{total:0.1f}G",
    "format-alt": "<span color='#7287fd'>SWAP:</span> <span color='#99d1db'>{swapUsed:0.1f}G</span>/{swapTotal:0.1f}G",
    "tooltip-format": "RAM:  {used:0.1f}G / {total:0.1f}G ({percentage}%)\nSWAP: {swapUsed:0.1f}G / {swapTotal:0.1f}G ({swapPercentage}%)",
    "states": {
      "warning": 80,
      "critical": 90
    }
  }
}
EOF
    echo "Generated ${OUT_MEM} (RAM + SWAP, swap detected)."
else
    cat > "$OUT_MEM" << 'EOF'
// Generated by install/waybar.sh — do not edit manually.
// No swap detected: RAM only.
{
  "memory": {
    "interval": 5,
    "format": "<span color='#7287fd'>RAM:</span> <span color='#99d1db'>{used:0.1f}G</span>/{total:0.1f}G",
    "tooltip-format": "RAM: {used:0.1f}G / {total:0.1f}G ({percentage}%)",
    "states": {
      "warning": 80,
      "critical": 90
    }
  }
}
EOF
    echo "Generated ${OUT_MEM} (RAM only, no swap)."
fi
