#!/usr/bin/env bash
#
# waybar.sh — install-time waybar configuration.
#
# Generates modules-cpu.jsonc with exactly one bar icon slot per logical CPU
# core (from nproc). The built-in waybar "cpu" module only populates {iconN}
# placeholders up to the actual core count; extra placeholders render as literal
# text and break the widget, so the count must match the hardware.
#
# The generated file is included by config-top / config-bottom and is gitignored.
# Re-run this script if you move the config to a machine with a different core
# count.

set -euo pipefail

WAYBAR_DIR="${WAYBAR_DIR:-$HOME/.config/waybar}"
OUT="${WAYBAR_DIR}/modules-cpu.jsonc"

CORES="$(nproc)"
[[ "$CORES" -ge 1 ]] || CORES=1

# Build the per-core icon placeholder string: {icon0}{icon1}...{icon(N-1)}
ICONS=""
for ((i = 0; i < CORES; i++)); do
    ICONS+="{icon${i}}"
done

mkdir -p "$WAYBAR_DIR"

cat > "$OUT" << EOF
// Generated by install/waybar.sh — do not edit manually.
// One {iconN} slot per logical CPU core (detected: ${CORES}).
{
  "cpu": {
    "interval": 1,
    "format": "<span color='#ef9f76'>CPU:</span> ${ICONS}",
    "format-icons": [
      "<span color='#69ff94'>▁</span>",
      "<span color='#2aa9ff'>▂</span>",
      "<span color='#f8f8f2'>▃</span>",
      "<span color='#f8f8f2'>▄</span>",
      "<span color='#ffffa5'>▅</span>",
      "<span color='#ffffa5'>▆</span>",
      "<span color='#ff9977'>▇</span>",
      "<span color='#dd532e'>█</span>"
    ]
  }
}
EOF

echo "Generated ${OUT} for ${CORES} CPU core(s)."
