#!/usr/bin/env bash
#
# apply-monitor-vars.sh
# Single source of truth: reads monitor-vars.conf and propagates connector names
# to all consumers that can't use Hyprland's native $monitorN variables.
#
# Run at login (exec-once in hyprland.conf). Also safe to re-run manually after
# editing monitor-vars.conf.
#
# Consumers:
#   - config/hypr/hyprpaper.conf     (generated from hyprpaper.conf.tpl)
#   - config/hypr/monitor-env.sh     (sourced by waybar/launch.sh and other scripts)
#
# Hyprland itself (workspaces.conf, input.conf) reads monitor-vars.conf directly
# via native $monitorN variables — no action needed here for those.

set -euo pipefail

VARS_CONF="${MONITOR_VARS_CONF:-$HOME/.config/hypr/hyprland/monitor-vars.conf}"
TPL="${HOME}/.config/hypr/hyprpaper.conf.tpl"
OUT_HYPRPAPER="${HOME}/.config/hypr/hyprpaper.conf"
OUT_ENV="${HOME}/.config/hypr/monitor-env.sh"

# ── Parse monitor-vars.conf ───────────────────────────────────────────────────
declare -A MONITORS  # MONITORS[1]=DP-1, MONITORS[2]=DP-6, MONITORS[3]=eDP-1

while IFS= read -r line; do
    if [[ "$line" =~ ^\$monitor([0-9]+)[[:space:]]*=[[:space:]]*([^[:space:]#]+) ]]; then
        MONITORS["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
    fi
done < "$VARS_CONF"

for n in 1 2 3; do
    if [[ -z "${MONITORS[$n]:-}" ]]; then
        echo "warning: \$monitor${n} not found in ${VARS_CONF}, skipping." >&2
    fi
done

M1="${MONITORS[1]:-}"
M2="${MONITORS[2]:-}"
M3="${MONITORS[3]:-}"

# ── Generate monitor-env.sh (sourced by bash scripts) ────────────────────────
cat > "$OUT_ENV" << EOF
# Generated by apply-monitor-vars.sh — do not edit manually.
# Source this file in bash scripts to get monitor connector names.
export MONITOR1="${M1}"
export MONITOR2="${M2}"
export MONITOR3="${M3}"
EOF
echo "Generated ${OUT_ENV}"

# ── Generate hyprpaper.conf from template ─────────────────────────────────────
if [[ ! -f "$TPL" ]]; then
    echo "error: template not found: ${TPL}" >&2
    exit 1
fi

sed \
    -e "s|{{MONITOR1}}|${M1}|g" \
    -e "s|{{MONITOR2}}|${M2}|g" \
    -e "s|{{MONITOR3}}|${M3}|g" \
    "$TPL" > "$OUT_HYPRPAPER"
echo "Generated ${OUT_HYPRPAPER}"
