# Set the directory we want to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Add in zsh plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

# Lazy load NVM for faster shell startup
export NVM_COMPLETION=true
export NVM_LAZY_LOAD=true
export NVM_SYMLINK_CURRENT="true"
zinit wait lucid light-mode for lukechilds/zsh-nvm

# Add in snippets
zinit snippet OMZL::git.zsh
zinit snippet OMZP::git
zinit snippet OMZP::sudo
zinit snippet OMZP::archlinux
zinit snippet OMZP::command-not-found

# Load completions
autoload -Uz compinit && compinit

zinit cdreplay -q

# Keybindings
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# ============================================
# Aliases
# ============================================

# Basic aliases
alias ls='ls --color'
alias vim='nvim'
alias v='nvim .'
alias v.='nvim .'
alias c='clear'
alias ll='ls -la'
alias update='sudo pacman -Syyu;yay -Su'
alias cleanup='sudo pacman -Rns $(pacman -Qtdq);yay -Sc --noconfirm'

# Navigation
alias al="vim ~/.config/aliases"
alias proj="cd ~/projects"
alias secrets="vim ~/.local/.secrets"
alias gc="cd $HOME/.config"
alias hosts="sudo nvim /etc/hosts"
alias i3conf="vim ~/.config/i3/config"
alias hyprconf="vim ~/.config/hypr/hyprland.conf"
alias zconf="vim ~/.zshrc"

# Pacman & Package Management
alias unlock="sudo rm /var/lib/pacman/db.lck"
alias rmpacmanlock="sudo rm /var/lib/pacman/db.lck"
alias pci="sudo pacman -Sy --noconfirm"
alias pcr="sudo pacman -Runs --noconfirm"
alias pcs="pacman -Ss"
alias pcq="pacman -Qi"
alias yi="yay -Sy --noconfirm"
alias yr="yay -Runs --noconfirm"
alias yq="yay -Qi"
alias yl="yay -Qdt"

# Mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 30 --number 10 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 30 --number 10 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 30 --number 10 --sort age --save /etc/pacman.d/mirrorlist"

# Docker
alias dids="docker container ls | cut -d ' ' -f1 | sed 1d"
alias drun="docker container run"
alias dkill="docker container kill"
alias dsh="run_bash_in_docker_container"

# Maven
alias mvn-ci="mvn clean install"
alias mvn-ci-sk="mvn clean install -DskipTests"
alias mvn-it="mvn failsafe:integration-test"
alias mvn-check-updates="mvn versions:display-property-updates"

# Tmux
alias tconf="nvim ~/.config/tmux/tmux.conf"
alias tls="tmux ls"
alias tn="tmux new -s "
alias ts="$SCRIPTS/cli/sessionizer.sh"
alias t="$SCRIPTS/cli/sessionizer.sh"
alias term="t term"
alias dev="t dev"

# Terraform
alias tf="terraform"

# Neovim flavors
alias nvchad="NVIM_APPNAME=nvchad nvim"
alias lazyvim="NVIM_APPNAME=lazyvim nvim"
alias astronvim="NVIM_APPNAME=astronvim nvim"

# Systemd services
alias sactivate="sudo systemctl enable --now"
alias sdeactivate="sudo systemctl disable --now"
alias sstart="sudo systemctl start"
alias sstop="sudo systemctl stop"
alias srestart="sudo systemctl restart"
alias sstatus="sudo systemctl status"

# Screen layouts (X11/autorandr specific)
alias shome="~/.screenlayout/home.sh"
alias swork="~/.screenlayout/work.sh"
alias srhome="~/.screenlayout/reset.sh"
alias sralone="~/.screenlayout/reset-standalone.sh"
alias salone="~/.screenlayout/standalone.sh"

# Utilities
alias freeram="~/.local/bin/scripts/freeram.sh"
alias CAPS="xdotool key Caps_Lock"
alias rcp="rsync -ah --progress"

# AWS (if using CS)
alias awscreds="source aws-expose-creds"
alias awsclear="export AWS_PROFILE="
alias chrome="chromium --disable-web-security --user-data-dir=\"$HOME/.dummy-chrome-data\""

# Launch with devour (X11)
alias arandr="devour arandr"
alias zoom="devour ~/.local/bin/zoom"

# ============================================
# Functions
# ============================================

# ex - EXtractor for all kinds of archives
# usage: ex <file>
ex() {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   tar xf $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# Git checkout remote branch
function gitr() {
  git fetch -a && git checkout -b $1 origin/$1
}

# Tmux session manager
function tm() {
  if [[ -z $1 ]]; then
    tmux
  else
    tmux new -s $1
  fi
}

# AWS CodeArtifact login for CS
function csyarnlogin() {
  awscreds
  csq aws codeartifact login --tool yarn
}

# Map drawing tablet to screen (X11)
xppen() {
  tablet="UGTABLET 6 inch PenTablet Pen (0)"
  selected_screen=$(xrandr --query | grep " connected" | awk '{print $1}' | fzf --prompt="Select screen for tablet: ")
  if [ -n "$selected_screen" ]; then
    xinput map-to-output "$tablet" "$selected_screen"
    echo "Tablet mapped to $selected_screen"
  else
    echo "Screen selection cancelled"
  fi
}

# ============================================
# Load additional aliases from config
# ============================================
AL_PATH="$HOME/.config/aliases"
if [ -d "$AL_PATH" ]; then
  for a in $(ls -L $AL_PATH 2>/dev/null); do
    source $AL_PATH/$a
  done
fi

# ============================================
# Shell integrations
# ============================================

# FZF
eval "$(fzf --zsh)"

# zoxide (smart cd replacement) - install with: pacman -S zoxide
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init --cmd cd zsh)"
fi

# ============================================
# Theme Selection
# ============================================

# Choose your theme: 'agnoster' or 'starship'
# Comment/uncomment the one you want to use

# Option 1: Agnoster (via oh-my-zsh)
if [ -f "$HOME/.oh-my-zsh/oh-my-zsh.sh" ]; then
  export ZSH="$HOME/.oh-my-zsh"
  ZSH_THEME="agnoster"
  source $ZSH/oh-my-zsh.sh
fi


if [ -n "$TMUX" ]; then
  fastfetch --logo none
else
  fastfetch 
fi

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8


export BROWSER=firefox
export EDITOR=nvim
export VISUAL=nvim
export PAGER=less
export TERMINAL=kitty

# Option 2: Starship prompt (comment out agnoster above to use this)
# if command -v starship &> /dev/null; then
#   # https://github.com/starship/starship/issues/560#issuecomment-2339030231
#   precmd() { precmd() { echo "" } }
#   alias clear="precmd() { precmd() { echo } } && clear"
#   eval "$(starship init zsh)"
# fi
